# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y sudo curl
  SHELL

  config.vm.define "stretch" do |stretch|
    stretch.vm.box = "debian/stretch64"
  end
  config.vm.define "buster" do |buster|
    buster.vm.box = "debian/buster64"
  end
  config.vm.define "bionic" do |bionic|
    bionic.vm.box = "ubuntu/bionic64"
  end
  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "ubuntu/xenial64"
  end

end
