version: '2'
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile-mysterium-node
      args:
        VERSION: 0.0.6
    container_name: mysterium-node
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    ports:
      - 1194:1194
    volumes:
      - .:/application
    environment:
      - NODE=123456

  client:
    build:
      context: .
      dockerfile: Dockerfile-mysterium-client
      args:
        PACKAGE_FILE: build/package/mysterium-client_linux_amd64.deb
    container_name: mysterium-client
    networks:
      - default
    volumes:
      - .:/application

  gateway:
    image: nats
    container_name: mysterium-gateway
    networks:
      - default
    ports:
      - 4222:4222
      - 8222:8222