version: '3.0'

services:
  morqa:
    image: mysteriumnetwork/quality-oracle:latest
    command: >
      - '--bind-addr=:8085'
      - '--prometheus=http://prometheus:9090'
      - '--metrics-addr=:8080'
    depends_on:
      - prometheus
    expose:
      - 8085
      - 8080
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.198
      public1:
        ipv4_address: 172.31.0.198

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./e2e/prometheus:/prometheus
    command:
      - '--config.file=/prometheus/prometheus-local.yml'
      - '--storage.tsdb.path=/data'
    expose:
      - 9090
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.199
      public1:
        ipv4_address: 172.31.0.199

  ipify:
    image: owlab/ipify
    expose:
      - 3000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.10
      public1:
        ipv4_address: 172.31.0.10

  broker-real:
    image: nats:1.0.4
    expose:
      - 4222
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.30
      public1:
        ipv4_address: 172.31.0.30

  broker:
    image: mysteriumnetwork/nats-proxy:1.0.1
    depends_on:
      - broker-real
    expose:
      - 4222
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.31
      public1:
        ipv4_address: 172.31.0.31

  db:
    image: percona:5.7
    cap_add:
      - NET_ADMIN
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.201
      public1:
        ipv4_address: 172.31.0.201

  mysterium-api:
    image: mysteriumnetwork/mysterium-api:0.5.22
    expose:
      - 8001
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    environment:
      APP_PORT: 8001
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "http://ganache:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
      DISCOVERY_VERIFY_IDENTITY: "false"
    depends_on:
      - db
      - ganache
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.200
      public1:
        ipv4_address: 172.31.0.200

  # private blockchain
  ganache:
    image: trufflesuite/ganache-cli:v6.6.0-beta.0
    expose:
      - 8545
    command: >
      --mnemonic "amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger"
    dns: 172.30.0.254
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    networks:
      public0:
        ipv4_address: 172.30.0.202
      public1:
        ipv4_address: 172.31.0.202

  transactor:
    image: mysteriumnetwork/transactor:0.1.0
    environment:
      PORT: 8888
    expose:
      - 8888
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    depends_on:
      - ganache
    command: >
      -mystSCAddress 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint http://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -ourIdentity 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -balanceCheckInterval 1s
    volumes:
      - ./e2e/blockchain/keystore:/keystore
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.203
      public1:
        ipv4_address: 172.31.0.203

  hermes:
    image: mysteriumnetwork/accountant:0.2
    environment:
      PORT: 8889
    expose:
      - 8889
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    depends_on:
      - ganache
      - mongodb
    command: >
      -identityPassphrase ""
      -myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint http://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -operator 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -keystoreDir /keystore
      -hermesAddress 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -MongoUser hermes
      -MongoPass hermes
      -MongoHost "mongodb:27017"
      -MongoReplSet ""
    volumes:
      - ./e2e/blockchain/keystore:/keystore
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.204
      public1:
        ipv4_address: 172.31.0.204

  mongodb:
    image: 'mongo:4.2.3'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=hermes
      - MONGO_NON_ROOT_USERNAME=hermes
      - MONGO_NON_ROOT_PASSWORD=hermes
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.205
      public1:
        ipv4_address: 172.31.0.205
    expose:
      - 27017
      - 27018
      - 27019
    volumes:
      - ./e2e/mongo-init.e2e.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  myst-consumer:
    build:
      context: .
      dockerfile: ./localnet/node/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    depends_on:
      - forwarder
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 4050
    volumes:
    - ./localnet/volume/consumer:/var/lib/mysterium-node
    - ./:/node
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.101

  myst-provider:
    build:
      context: .
      dockerfile: ./localnet/node/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.0.2
    depends_on:
      - forwarder2
      - broker
      - mysterium-api
      - ipify
      - transactor
      - hermes
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 1194
      - 4050
    volumes:
      - ./localnet/volume/provider:/var/lib/mysterium-node
      - ./:/node
    dns: 172.31.0.254
    networks:
      priv0:
        ipv4_address: 10.100.0.102

  go-runner:
    build:
      context: .
      dockerfile: ./e2e/gorunner/Dockerfile
    volumes:
      - ./:/node
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /node
    dns: 172.30.0.254
    cap_add:
      - NET_ADMIN
    networks:
      public0:
        ipv4_address: 172.30.0.222
      public1:
        ipv4_address: 172.31.0.222
      priv0:
        ipv4_address: 10.100.0.222
      priv1:
        ipv4_address: 10.100.1.222

  router:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_NAT=172.30.0.1
    networks:
      public0:
        ipv4_address: 172.30.0.254
      public1:
        ipv4_address: 172.31.0.254

  forwarder:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.2
      priv1:
        ipv4_address: 10.100.1.2

  forwarder2:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.31.0.254
    dns: 172.31.0.254
    networks:
      public1:
        ipv4_address: 172.31.0.2
      priv0:
        ipv4_address: 10.100.0.2

networks:
  public0:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  public1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.31.0.0/24
  priv0:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.0.0/24
  priv1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.1.0/24
