FROM ubuntu:16.04
MAINTAINER Valdas Petrulis <petrulis.valdas@gmail.com>

ENV VERSION 0.0.6
ENV NODE 321

# Install packages
RUN apt-get update \
    && apt install -y --no-install-recommends wget ca-certificates \
    && wget https://github.com/MysteriumNetwork/node/releases/download/${VERSION}/mysterium-node_linux_amd64.deb \
    && dpkg --install --force-depends mysterium-node_linux_amd64.deb\
    && apt-get install -y --fix-broken \
    && rm -rf /var/cache/apk/* \
    && rm mysterium-node_linux_amd64.deb

COPY entrypoint-node.sh /entrypoint-node.sh
RUN chmod +x /entrypoint-node.sh

ENTRYPOINT ["/entrypoint-node.sh"]
CMD mysterium_server --config-dir=/etc/mysterium-node --node=${NODE} --runtime-dir=/tmp
