version: '3.0'

services:
  morqa:
    image: mysteriumnetwork/quality-oracle:latest
    command: >
      --bind-addr=:8085
      --prometheus=http://prometheus:9090
      --metrics-addr=:8080
    depends_on:
      - prometheus
    expose:
      - 8085
      - 8080
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.198
      public1:
        ipv4_address: 172.31.0.198

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - ./e2e/prometheus:/prometheus
    command:
      - '--config.file=/prometheus/config.yml'
      - '--storage.tsdb.path=data/'
    expose:
      - 9090
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.199
      public1:
        ipv4_address: 172.31.0.199

  ipify:
    image: owlab/ipify
    expose:
      - 3000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.10
      public1:
        ipv4_address: 172.31.0.10

  broker:
    image: nats:1.0.4
    expose:
      - 4222
      - 8222
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.30
      public1:
        ipv4_address: 172.31.0.30

  db:
    image: postgres:13-alpine
    container_name: discovery_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=discovery
      - POSTGRES_DB=discovery
      - POSTGRES_PASSWORD=discovery
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.201
      public1:
        ipv4_address: 172.31.0.201

  discovery:
    image: mysteriumnetwork/discovery:latest
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8080
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    environment:
      - PORT=8080
      - DB_DSN=postgresql://discovery:discovery@db:5432/discovery
      - QUALITY_ORACLE_URL=http://morqa:8085
      - BROKER_URL=broker
    depends_on:
      - db
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.200
      public1:
        ipv4_address: 172.31.0.200

  # private blockchain
  ganache:
    image: trufflesuite/ganache-cli:v6.12.0
    expose:
      - 8545
    command: >
      --chainId 5 --mnemonic "amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger"
    dns: 172.30.0.254
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    networks:
      public0:
        ipv4_address: 172.30.0.202
      public1:
        ipv4_address: 172.31.0.202

  trust:
    image: mysteriumnetwork/trust-oracle:latest
    command: >
      -swaggerHost=trust
      -trustedIDs=0xc4cb9a91b8498776f6f8a0d5a2a23beec9b3cef3
    dns: 172.30.0.254
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    networks:
      public0:
        ipv4_address: 172.30.0.207
      public1:
        ipv4_address: 172.31.0.207

  http-mock:
    image: mockserver/mockserver:mockserver-5.11.2
    dns: 172.30.0.254
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    ports:
      - 9999:1080
    networks:
      public0:
        ipv4_address: 172.30.0.211
      public1:
        ipv4_address: 172.31.0.211


  transactor:
    image: mysteriumnetwork/transactor:0.8.0
    environment:
      PORT: 8888
    expose:
      - 8888
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    depends_on:
      - ganache
      - redis
      - mongodb
      - http-mock
    command: >
      -overrideGasStation=true
      -geckoUrl=http://http-mock:1080/gecko
      -chain1RPCEndpoint ws://ganache:8545
      -chain1ChainID 5
      -stakeAmount 62000000000000000000
      -topUpAmount 7000000000000000000
      -chain1MystSCAddress 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -chain1Registry 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -ourIdentity 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chain1ChImplementation 0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      -balanceCheckInterval 1s
      -MongoUser transactor
      -MongoPass transactor
      -MongoHost mongodb:27017
      -MongoReplSet ""
      -freeRegistration=true
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.203
      public1:
        ipv4_address: 172.31.0.203

  hermes:
    image: mysteriumnetwork/hermes:0.8.0
    environment:
      PORT: 8889
    expose:
      - 8889
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    depends_on:
      - ganache
      - redis
      - mongodb
    command: >
      -identityPassphrase ""
      -Chain1Myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -Chain1RPCEndpoint ws://ganache:8545
      -Chain1ChainID 5
      -Chain1Registry 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -operator 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -Chain1chImplementation 0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      -keystoreDir /keystore
      -Chain1HermesAddress 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -bcDataRefreshInterval 1ns
      -MongoUser hermes
      -transactorBaseUri "http://transactor:8888/api/v1/"
      -MongoPass hermes
      -MongoHost "mongodb:27017"
      -MongoDatabase hermes
      -MongoReplSet ""
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.204
      public1:
        ipv4_address: 172.31.0.204

  redis:
    image: bitnami/redis:5.0.8
    container_name: 'hermes_redis'
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.206
      public1:
        ipv4_address: 172.31.0.206

  mongodb:
    image: 'mongo:4.2.3'
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_DATABASE=hermes
      - MONGO_NON_ROOT_USERNAME=hermes
      - MONGO_NON_ROOT_PASSWORD=hermes
    expose:
      - 27017
      - 27018
      - 27019
    volumes:
      - ./e2e/mongo-init.e2e.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.205
      public1:
        ipv4_address: 172.31.0.205

  myst-consumer-hermes2:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
      - transactor
      - hermes2
      - myst-provider
      - morqa
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --chains.1.myst=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --chains.1.registry=0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      --chains.1.channelImplementation=0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      --chains.1.hermes=0x66D0a6DD6c1120B0e11513A4bA439f6eaed0E0Ed
      --transactor.address=http://transactor:8888/api/v1
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://discovery:8080/api/v3
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v2
      --stun-servers=""
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.105

  hermes2:
    image: mysteriumnetwork/hermes:0.8.0
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    environment:
      PORT: 8889
    expose:
      - 8889
    depends_on:
      - ganache
      - redis
      - mongodb
    command: >
      -identityPassphrase ""
      -Chain1Myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -Chain1RPCEndpoint ws://ganache:8545
      -Chain1ChainID 5
      -Chain1Registry 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -operator 0x761f2bb3e7ad6385a4c7833c5a26a8ddfdabf9f3
      -Chain1chImplementation 0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      -keystoreDir /keystore
      -transactorBaseUri "http://transactor:8888/api/v1/"
      -Chain1HermesAddress 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -bcDataRefreshInterval 1ns
      -MongoUser hermes2
      -MongoPass hermes2
      -MongoHost "mongodb:27017"
      -MongoDatabase hermes2
      -MongoReplSet ""
      -redisAddress "redis:6379"
    volumes:
      - ./e2e/blockchain/keystore:/keystore
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.208
      public1:
        ipv4_address: 172.31.0.208

  myst-consumer-wireguard:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    depends_on:
      - forwarder
      - broker
      - discovery
      - ipify
      - transactor
      - hermes
      - morqa
      - ganache
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --payments.bc.timeout=1s
      --chains.1.myst=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual \
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://discovery:8080/api/v3
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --chains.1.registry=0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      --chains.1.channelImplementation=0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      --chains.1.hermes=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --transactor.address=http://transactor:8888/api/v1
      --quality.address=http://morqa:8085/api/v2
      --firewall.killSwitch.always
      --stun-servers=""
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.101


  myst-consumer-openvpn:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
      - transactor
      - hermes
      - myst-provider
      - morqa
      - ganache
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --chains.1.registry=0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      --chains.1.channelImplementation=0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      --chains.1.hermes=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --chains.1.myst=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.address=http://transactor:8888/api/v1
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://discovery:8080/api/v3
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v2
      --stun-servers=""
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.103

  myst-consumer-noop:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    volumes:
      - ./e2e/myst-consumer/keystore/remember.json:/var/lib/mysterium-node/keystore/remember.json
      - ./e2e/myst-consumer/keystore/UTC--2020-07-31T02-37-15.148642000Z--c4cb9a91b8498776f6f8a0d5a2a23beec9b3cef3:/var/lib/mysterium-node/keystore/UTC--2020-07-31T02-37-15.148642000Z--c4cb9a91b8498776f6f8a0d5a2a23beec9b3cef3
    depends_on:
      - broker
      - discovery
      - ipify
      - transactor
      - hermes
      - myst-provider
      - morqa
      - ganache
    cap_add:
      - NET_ADMIN
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --chains.1.myst=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --chains.1.registry=0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      --chains.1.hermes=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --transactor.address=http://transactor:8888/api/v1
      --chains.1.channelImplementation=0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --log-level=debug
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --api.address=http://discovery:8080/api/v3
      --ether.client.rpc=ws://ganache:8545
      --keystore.lightweight
      --firewall.killSwitch.always
      --quality.address=http://morqa:8085/api/v2
      --stun-servers=""
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.104

  myst-provider:
    build:
      context: .
      dockerfile: ./bin/docker/alpine-prebuilt/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.0.2
    depends_on:
      - forwarder2
      - broker
      - discovery
      - ipify
      - transactor
      - hermes
      - hermes2
      - morqa
      - trust
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    expose:
      - 1194
      - 4050
    volumes:
      - ./e2e/myst-provider/keystore:/var/lib/mysterium-node/keystore
    command: >
      --discovery.ping=1s
      --discovery.fetch=1s
      --chains.1.myst=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-land
      --broker-address=broker
      --tequilapi.address=0.0.0.0
      --firewall.protected.networks=""
      --api.address=http://discovery:8080/api/v3
      --ether.client.rpc=ws://ganache:8545
      --chains.1.registry=0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      --chains.1.hermes=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --chains.1.channelImplementation=0xAA9C4E723609Cb913430143fbc86D3CBe7ADCa21
      --transactor.address=http://transactor:8888/api/v1
      --keystore.lightweight
      --log-level=debug
      --quality.address=http://morqa:8085/api/v2
      --payments.provider.invoice-frequency=1s
      --access-policy.address=http://trust:8080/api/v1/access-policies/
      --access-policy.fetch=1s
      --stun-servers=""
      service
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      openvpn,wireguard,noop
    dns: 172.31.0.254
    networks:
      priv0:
        ipv4_address: 10.100.0.102

  go-runner:
    build:
      context: .
      dockerfile: ./e2e/gorunner/Dockerfile.precompiled
    volumes:
      - ./e2e/blockchain/keystore:/node/keystore
    working_dir: /node
    dns: 172.30.0.254
    cap_add:
      - NET_ADMIN
    networks:
      public0:
        ipv4_address: 172.30.0.222
      public1:
        ipv4_address: 172.31.0.222
      priv0:
        ipv4_address: 10.100.0.222
      priv1:
        ipv4_address: 10.100.1.222

  router:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_NAT=172.30.0.1
    networks:
      public0:
        ipv4_address: 172.30.0.254
      public1:
        ipv4_address: 172.31.0.254

  forwarder:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.2
      priv1:
        ipv4_address: 10.100.1.2

  forwarder2:
    build:
      context: .
      dockerfile: ./e2e/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.31.0.254
    dns: 172.31.0.254
    networks:
      public1:
        ipv4_address: 172.31.0.2
      priv0:
        ipv4_address: 10.100.0.2

networks:
  public0:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  public1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.31.0.0/24
  priv0:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.0.0/24
  priv1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.1.0/24
