version: '2.4'

services:
  ipify:
    image: owlab/ipify
    expose:
      - 3000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.10
      public2:
        ipv4_address: 172.31.0.10

  broker:
    image: nats
    expose:
      - 4222
      - 8222
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.30
      public2:
        ipv4_address: 172.31.0.30

  db:
    image: percona:5.7
    cap_add:
      - NET_ADMIN
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.201
      public2:
        ipv4_address: 172.31.0.201

  geth:
    image: mysteriumnetwork/geth:1.8.23
    expose:
      - 8545
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - geth-runtime:/ethereum/geth-runtime
      - ./geth/genesis.json:/ethereum/genesis.json
      - ./geth/keystore:/ethereum/keystore
      - ./geth/node_acc_password.txt:/ethereum/node_acc_password.txt
    command: >
      --syncmode 'full'
      --port 30311
      --rpc
      --rpcaddr '0.0.0.0'
      --rpcport 8545
      --rpcapi personal,db,eth,net,web3,txpool,miner
      --networkid 69
      --gasprice '1'
      --unlock '0xd9786b6ee6caf5cd0ef88301fc40de83bfac5594'
      --password node_acc_password.txt
      --rpcvhosts *
      --rpccorsdomain *
      --mine
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.202
      public2:
        ipv4_address: 172.31.0.202

  mysterium-api:
    image: mysteriumnetwork/mysterium-api:0.5.9
    expose:
      - 80
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "http://geth:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
      DISCOVERY_VERIFY_IDENTITY: "false"
    depends_on:
      - db
      - geth
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.200
      public2:
        ipv4_address: 172.31.0.200

  router:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_NAT=172.30.0.1
    volumes:
      - ../../e2e/config/named.conf:/etc/bind/named.conf
    networks:
      public:
        ipv4_address: 172.30.0.254
      public2:
        ipv4_address: 172.31.0.254

  forwarder:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    volumes:
      - ../../e2e/config/named.conf:/etc/bind/named.conf
    environment:
      - GATEWAY=172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.2
      priv1:
        ipv4_address: 10.100.0.2

  forwarder2:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    volumes:
      - ../../e2e/config/named.conf:/etc/bind/named.conf
    environment:
      - GATEWAY=172.31.0.254
    dns: 172.31.0.254
    networks:
      public2:
        ipv4_address: 172.31.0.2
      priv2:
        ipv4_address: 10.100.1.2

  myst-consumer:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.0.2
    depends_on:
      - forwarder
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=http://geth:8545
      --keystore.lightweight
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.0.101

  myst-provider:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    depends_on:
      - forwarder2
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider:/var/lib/mysterium-node
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-traversal
      --broker-address=broker
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=http://geth:8545
      --keystore.lightweight
      service openvpn
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000
    dns: 172.31.0.254
    networks:
      priv2:
        ipv4_address: 10.100.1.102

  go-runner:
    image: golang:1.11
    volumes:
      - $GOPATH:/go
    working_dir: /go/src/github.com/mysteriumnetwork/node
    dns: 172.30.0.254
    networks:
      public:
        ipv4_address: 172.30.0.222

networks:
  public:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  public2:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.31.0.0/24
  priv1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.0.0/24
  priv2:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.1.0/24
volumes:
  geth-runtime:
