version: '3'
services:

  broker:
    image: nats:1.0.4
    expose:
      - 4222
      - 8222

  #infrastructure - centralized api and db
  db:
    image: percona:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  mysterium-api:
    image: mysteriumnetwork/mysterium-api:0.5.22
    ports:
      - 8001:8001
    expose:
    - 8001
    environment:
      APP_PORT: 8001
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "ws://ganache:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
      DISCOVERY_VERIFY_IDENTITY: "false"
    depends_on:
    - db
    - ganache

  #private blockchain
  ganache:
    image: trufflesuite/ganache-cli:v6.6.0-beta.0
    ports:
      - 8545:8545
    expose:
      - 8545
    command: >
      --mnemonic "amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger"

  transactor:
    image: mysteriumnetwork/transactor:latest
    environment:
      PORT: 8888
    expose:
      - 8888
    depends_on:
      - ganache
    command: >
      -mystSCAddress 0x427C2BAD22335710Aec5e477f3E3AdCd313A9bcb
      -rpcEndpoint ws://ganache:8545
      -registry 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
      -ourIdentity 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -balanceCheckInterval 1s
    volumes:
      - "./deployer/keystore:/keystore"

  #go runner to run go programs inside localnet (usefull for contract deployment or e2e test running)
  go-runner:
    image: golang:1.11
    volumes:
      - $GOPATH:/go
    working_dir: /go/src/github.com/mysteriumnetwork/node
