/*
 * Copyright (C) 2018 The "MysteriumNetwork/node" Authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package connection

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/rs/zerolog/log"

	"github.com/mysteriumnetwork/node/core/connection"
	"github.com/mysteriumnetwork/node/core/connection/connectionstate"
	"github.com/mysteriumnetwork/node/core/ip"
	"github.com/mysteriumnetwork/node/firewall"
	wg "github.com/mysteriumnetwork/node/services/wireguard"
	"github.com/mysteriumnetwork/node/services/wireguard/key"
	"github.com/mysteriumnetwork/node/services/wireguard/wgcfg"
)

type startConn func(conf wgcfg.DeviceConfig) (wg.ConnectionEndpoint, error)

// Options represents connection options.
type Options struct {
	DNSScriptDir     string
	HandshakeTimeout time.Duration
}

// NewConnection returns new WireGuard connection.
func NewConnection(opts Options, ipResolver ip.Resolver, endpointFactory wg.EndpointFactory, handshakeWaiter HandshakeWaiter) (connection.Connection, error) {
	privateKey, err := key.GeneratePrivateKey()
	if err != nil {
		return nil, errors.Wrap(err, "could not generate private key")
	}

	return &Connection{
		done:                make(chan struct{}),
		stateCh:             make(chan connectionstate.State, 100),
		privateKey:          privateKey,
		opts:                opts,
		ipResolver:          ipResolver,
		connEndpointFactory: endpointFactory,
		handshakeWaiter:     handshakeWaiter,
	}, nil
}

// Connection which does wireguard tunneling.
type Connection struct {
	stopOnce sync.Once
	done     chan struct{}
	stateCh  chan connectionstate.State

	ports               []int
	privateKey          string
	ipResolver          ip.Resolver
	connectionEndpoint  wg.ConnectionEndpoint
	removeAllowedIPRule func()
	opts                Options
	connEndpointFactory wg.EndpointFactory
	handshakeWaiter     HandshakeWaiter
}

var _ connection.Connection = &Connection{}

// State returns connection state channel.
func (c *Connection) State() <-chan connectionstate.State {
	return c.stateCh
}

// Diag is used to start provider check
func (c *Connection) Diag() bool {
	return c.connectionEndpoint.Diag()
}

// Statistics returns connection statistics channel.
func (c *Connection) Statistics() (connectionstate.Statistics, error) {
	stats, err := c.connectionEndpoint.PeerStats()
	if err != nil {
		return connectionstate.Statistics{}, err
	}
	return connectionstate.Statistics{
		At:            time.Now(),
		BytesSent:     stats.BytesSent,
		BytesReceived: stats.BytesReceived,
	}, nil
}

// Start establish wireguard connection to the service provider.
func (c *Connection) Start(ctx context.Context, options connection.ConnectOptions) error {
	return c.start(ctx, c.startConn, options)
}

// Reconnect restarts a connection with a new options.
func (c *Connection) Reconnect(ctx context.Context, options connection.ConnectOptions) error {
	return c.start(ctx, c.restartConn, options)
}

func (c *Connection) start(ctx context.Context, start startConn, options connection.ConnectOptions) (err error) {
	log.Info().Msg("+++++++++++++++++++++++++++++++++++++++++++++++++++++ *Connection) start")

	var config wg.ServiceConfig
	if err = json.Unmarshal(options.SessionConfig, &config); err != nil {
		return errors.Wrap(err, "failed to unmarshal connection config")
	}

	var removeAllowedIPRule firewall.OutgoingRuleRemove
	removeAllowedIPRule, err = firewall.AllowIPAccess(config.Provider.Endpoint.IP.String())
	if err != nil {
		return errors.Wrap(err, "failed to add firewall exception for wireguard remote IP")
	}
	c.removeAllowedIPRule = removeAllowedIPRule

	defer func() {
		if err != nil {
			c.Stop()
		}
	}()

	c.stateCh <- connectionstate.Connecting

	if options.ProviderNATConn != nil {
		options.ProviderNATConn.Close()
		config.LocalPort = options.ProviderNATConn.LocalAddr().(*net.UDPAddr).Port
		config.Provider.Endpoint.Port = options.ProviderNATConn.RemoteAddr().(*net.UDPAddr).Port
	}

	var dnsIPs []string
	dnsIPs, err = options.Params.DNS.ResolveIPs(config.Consumer.DNSIPs)
	if err != nil {
		return errors.Wrap(err, "could not resolve DNS IPs")
	}

	log.Info().Msg("Starting new connection")
	var conn wg.ConnectionEndpoint
	conn, err = start(wgcfg.DeviceConfig{
		IfaceName:    "", // Interface name will be generated by connection endpoint.
		Subnet:       config.Consumer.IPAddress,
		PrivateKey:   c.privateKey,
		ListenPort:   config.LocalPort,
		DNS:          dnsIPs,
		DNSScriptDir: c.opts.DNSScriptDir,
		Peer: wgcfg.Peer{
			Endpoint:               &config.Provider.Endpoint,
			PublicKey:              config.Provider.PublicKey,
			AllowedIPs:             []string{"0.0.0.0/0", "::/0"},
			KeepAlivePeriodSeconds: 18,
		},
		ReplacePeers: true,
		ProxyPort:    options.Params.ProxyPort,
	})
	if err != nil {
		return errors.Wrap(err, "could not start new connection")
	}
	c.connectionEndpoint = conn

	log.Info().Msg("Waiting for initial handshake")
	if err = c.handshakeWaiter.Wait(ctx, conn.PeerStats, c.opts.HandshakeTimeout, c.done); err != nil {
		return errors.Wrap(err, "failed while waiting for a peer handshake")
	}

	c.stateCh <- connectionstate.Connected
	return nil
}

func (c *Connection) startConn(conf wgcfg.DeviceConfig) (wg.ConnectionEndpoint, error) {
	conn, err := c.connEndpointFactory()
	if err != nil {
		return nil, errors.Wrap(err, "failed to create new connection endpoint")
	}

	log.Info().Msg("Starting connection endpoint")
	if err := conn.StartConsumerMode(conf); err != nil {
		return nil, errors.Wrap(err, "failed to start connection endpoint")
	}

	return conn, nil
}

func (c *Connection) restartConn(conf wgcfg.DeviceConfig) (wg.ConnectionEndpoint, error) {
	var err error
	conn := c.connectionEndpoint
	log.Info().Msg("Restarting connection endpoint")

	if conn == nil {
		conn, err = c.connEndpointFactory()
		if err != nil {
			return nil, errors.Wrap(err, "failed to create new connection endpoint on restart")
		}
	}

	if err = conn.ReconfigureConsumerMode(conf); err != nil {
		return nil, fmt.Errorf("failed to restart connection endpoint: %w", err)
	}

	return conn, nil
}

// GetConfig returns the consumer configuration for session creation
func (c *Connection) GetConfig() (connection.ConsumerConfig, error) {
	publicKey, err := key.PrivateKeyToPublicKey(c.privateKey)
	if err != nil {
		return nil, errors.Wrap(err, "could not get public key from private key")
	}

	return wg.ConsumerConfig{
		PublicKey: publicKey,
		Ports:     c.ports,
	}, nil
}

// Stop stops wireguard connection and closes connection endpoint.
func (c *Connection) Stop() {
	c.stopOnce.Do(func() {
		log.Info().Msg("Stopping WireGuard connection")
		c.stateCh <- connectionstate.Disconnecting

		if c.removeAllowedIPRule != nil {
			c.removeAllowedIPRule()
		}

		if c.connectionEndpoint != nil {
			if err := c.connectionEndpoint.Stop(); err != nil {
				log.Error().Err(err).Msg("Failed to close wireguard connection")
			}
		}

		c.stateCh <- connectionstate.NotConnected

		close(c.stateCh)
		close(c.done)
	})
}
