FROM alpine:3.22

RUN apk add --no-cache bash gcc musl-dev make linux-headers iptables ipset ca-certificates openvpn bash sudo openresolv

COPY ./build/e2e/test /usr/local/bin/test
COPY ./build/e2e/deployer /usr/local/bin/deployer
