/*
 * Copyright (C) 2021 The "MysteriumNetwork/node" Authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package versionmanager

import (
	"fmt"
	"io"
	"net/http"
	"strings"
	"testing"

	"github.com/mysteriumnetwork/node/requests"

	"github.com/stretchr/testify/assert"
)

type httpClientMock struct {
	req *http.Request

	rMap map[string]*http.Response
}

func newHttpClientMock(rMap map[string]*http.Response) *httpClientMock {
	return &httpClientMock{
		rMap: rMap,
	}
}

func (m *httpClientMock) Do(req *http.Request) (*http.Response, error) {
	m.req = req
	resp, ok := m.rMap[req.URL.Path]
	if !ok {
		return nil, fmt.Errorf("response for path: %s not found", req.URL.Path)
	}
	return resp, nil
}

func (m *httpClientMock) DoRequestAndParseResponse(req *http.Request, resp interface{}) error {
	r, err := m.Do(req)
	if err != nil {
		return err
	}
	defer r.Body.Close()
	return requests.ParseResponseJSON(r, &resp)
}

func (m *httpClientMock) stub(rMap map[string]*http.Response) {
	m.rMap = rMap
}

func TestNodeUIReleases(t *testing.T) {
	// given
	rMap := map[string]*http.Response{
		"/repos/mysteriumnetwork/dvpn-web/releases": {StatusCode: 200, Status: "200 OK", Body: &readCloser{Reader: strings.NewReader(releasesJSON)}},
	}
	m := newHttpClientMock(rMap)
	g := newGithub(m)

	// expect
	releases, err := g.nodeUIReleases(66, 88)

	assert.NoError(t, err)
	assert.True(t, len(releases) > 0)

	query := m.req.URL.Query()
	assert.Equal(t, "88", query.Get("page"))
	assert.Equal(t, "66", query.Get("per_page"))
}

func TestNodeUIReleaseByVersion(t *testing.T) {
	// given
	rMap := map[string]*http.Response{
		"/repos/mysteriumnetwork/dvpn-web/releases":                 {StatusCode: 200, Status: "200 OK", Body: &readCloser{Reader: strings.NewReader(releasesJSON)}},
		"/repos/mysteriumnetwork/dvpn-web/releases/tags/1.4.0":      {StatusCode: 200, Status: "200 OK", Body: &readCloser{Reader: strings.NewReader(releaseByTagJSON)}},
		"/repos/mysteriumnetwork/dvpn-web/releases/56174865/assets": {StatusCode: 200, Status: "200 OK", Body: &readCloser{Reader: strings.NewReader(releaseByTagAssetsJSON)}},
	}
	m := newHttpClientMock(rMap)
	g := newGithub(m)

	// expect
	url, err := g.nodeUIDownloadURL("1.4.0")

	assert.NoError(t, err)
	assert.Equal(t, "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.4.0/dist.tar.gz", url.String())
}

type readCloser struct {
	io.Reader
	Closed bool
}

func (tc *readCloser) Close() error {
	tc.Closed = true
	return nil
}

var _ io.ReadCloser = (*readCloser)(nil)

var releaseByTagAssetsJSON = `[
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52841750",
		"id": 52841750,
		"node_id": "RA_kwDOCwMSYc4DJk0W",
		"name": "compatibility.json",
		"label": "",
		"uploader": {
			"login": "MysteriumTeam",
			"id": 42934344,
			"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
			"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/MysteriumTeam",
			"html_url": "https://github.com/MysteriumTeam",
			"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
			"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
			"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
			"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
			"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
			"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
			"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
			"type": "User",
			"site_admin": false
		},
		"content_type": "application/octet-stream",
		"state": "uploaded",
		"size": 37,
		"download_count": 1,
		"created_at": "2021-12-30T07:48:22Z",
		"updated_at": "2021-12-30T07:48:22Z",
		"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.4.0/compatibility.json"
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52841749",
		"id": 52841749,
		"node_id": "RA_kwDOCwMSYc4DJk0V",
		"name": "dist.tar.gz",
		"label": "",
		"uploader": {
			"login": "MysteriumTeam",
			"id": 42934344,
			"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
			"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/MysteriumTeam",
			"html_url": "https://github.com/MysteriumTeam",
			"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
			"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
			"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
			"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
			"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
			"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
			"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
			"type": "User",
			"site_admin": false
		},
		"content_type": "application/octet-stream",
		"state": "uploaded",
		"size": 1565486,
		"download_count": 1,
		"created_at": "2021-12-30T07:48:21Z",
		"updated_at": "2021-12-30T07:48:22Z",
		"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.4.0/dist.tar.gz"
	}
]
`

var releaseByTagJSON = `
{
	"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865",
	"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865/assets",
	"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865/assets{?name,label}",
	"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.4.0",
	"id": 56174865,
	"author": {
		"login": "mdomasevicius",
		"id": 20511486,
		"node_id": "MDQ6VXNlcjIwNTExNDg2",
		"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/mdomasevicius",
		"html_url": "https://github.com/mdomasevicius",
		"followers_url": "https://api.github.com/users/mdomasevicius/followers",
		"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
		"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
		"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
		"repos_url": "https://api.github.com/users/mdomasevicius/repos",
		"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
		"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
		"type": "User",
		"site_admin": false
	},
	"node_id": "RE_kwDOCwMSYc4DWSkR",
	"tag_name": "1.4.0",
	"target_commitish": "master",
	"name": "1.4.0",
	"draft": false,
	"prerelease": false,
	"created_at": "2021-12-30T07:33:43Z",
	"published_at": "2021-12-30T07:34:17Z",
	"assets": [
		{
			"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52841750",
			"id": 52841750,
			"node_id": "RA_kwDOCwMSYc4DJk0W",
			"name": "compatibility.json",
			"label": "",
			"uploader": {
				"login": "MysteriumTeam",
				"id": 42934344,
				"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
				"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/MysteriumTeam",
				"html_url": "https://github.com/MysteriumTeam",
				"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
				"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
				"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
				"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
				"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
				"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
				"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
				"type": "User",
				"site_admin": false
			},
			"content_type": "application/octet-stream",
			"state": "uploaded",
			"size": 37,
			"download_count": 1,
			"created_at": "2021-12-30T07:48:22Z",
			"updated_at": "2021-12-30T07:48:22Z",
			"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.4.0/compatibility.json"
		},
		{
			"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52841749",
			"id": 52841749,
			"node_id": "RA_kwDOCwMSYc4DJk0V",
			"name": "dist.tar.gz",
			"label": "",
			"uploader": {
				"login": "MysteriumTeam",
				"id": 42934344,
				"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
				"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/MysteriumTeam",
				"html_url": "https://github.com/MysteriumTeam",
				"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
				"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
				"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
				"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
				"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
				"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
				"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
				"type": "User",
				"site_admin": false
			},
			"content_type": "application/octet-stream",
			"state": "uploaded",
			"size": 1565486,
			"download_count": 1,
			"created_at": "2021-12-30T07:48:21Z",
			"updated_at": "2021-12-30T07:48:22Z",
			"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.4.0/dist.tar.gz"
		}
	],
	"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.4.0",
	"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.4.0",
	"body": "## What's Changed\r\n* Node UI version manager by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/253\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.3.1...1.4.0",
	"mentions_count": 1
}
`

var releasesJSON = `
[
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/56174865/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.4.0",
		"id": 56174865,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DWSkR",
		"tag_name": "1.4.0",
		"target_commitish": "master",
		"name": "1.4.0",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-30T07:33:43Z",
		"published_at": "2021-12-30T07:34:17Z",
		"assets": [],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.4.0",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.4.0",
		"body": "## What's Changed\r\n* Node UI version manager by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/253\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.3.1...1.4.0",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56127627",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56127627/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/56127627/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.3.1",
		"id": 56127627,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DWHCL",
		"tag_name": "1.3.1",
		"target_commitish": "master",
		"name": "1.3.1",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-29T09:35:46Z",
		"published_at": "2021-12-29T09:36:06Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52779136",
				"id": 52779136,
				"node_id": "RA_kwDOCwMSYc4DJViA",
				"name": "compatibility.json",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 37,
				"download_count": 3,
				"created_at": "2021-12-29T09:45:22Z",
				"updated_at": "2021-12-29T09:45:22Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.1/compatibility.json"
			},
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52779135",
				"id": 52779135,
				"node_id": "RA_kwDOCwMSYc4DJVh_",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1556153,
				"download_count": 3,
				"created_at": "2021-12-29T09:45:21Z",
				"updated_at": "2021-12-29T09:45:22Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.1/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.3.1",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.3.1",
		"body": "## What's Changed\r\n* Quick fix config url parsing by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/252\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.3.0...1.3.1",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56124721",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56124721/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/56124721/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.3.0",
		"id": 56124721,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DWGUx",
		"tag_name": "1.3.0",
		"target_commitish": "master",
		"name": "1.3.0",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-29T08:25:04Z",
		"published_at": "2021-12-29T08:26:11Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52776258",
				"id": 52776258,
				"node_id": "RA_kwDOCwMSYc4DJU1C",
				"name": "compatibility.json",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 37,
				"download_count": 1,
				"created_at": "2021-12-29T08:34:54Z",
				"updated_at": "2021-12-29T08:34:55Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.0/compatibility.json"
			},
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52776257",
				"id": 52776257,
				"node_id": "RA_kwDOCwMSYc4DJU1B",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1556715,
				"download_count": 5,
				"created_at": "2021-12-29T08:34:54Z",
				"updated_at": "2021-12-29T08:34:54Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.0/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.3.0",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.3.0",
		"body": "## What's Changed\r\n* Basic cardinity fiat payments by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/249\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.2.2...1.3.0",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56091095",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/56091095/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/56091095/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.2.2",
		"id": 56091095,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DV-HX",
		"tag_name": "1.2.2",
		"target_commitish": "master",
		"name": "1.2.2",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-24T09:23:32Z",
		"published_at": "2021-12-28T15:30:39Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52730265",
				"id": 52730265,
				"node_id": "RA_kwDOCwMSYc4DJJmZ",
				"name": "compatibility.json",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 37,
				"download_count": 1,
				"created_at": "2021-12-28T15:35:20Z",
				"updated_at": "2021-12-28T15:35:21Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.2.2/compatibility.json"
			},
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52730263",
				"id": 52730263,
				"node_id": "RA_kwDOCwMSYc4DJJmX",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1538923,
				"download_count": 2,
				"created_at": "2021-12-28T15:35:18Z",
				"updated_at": "2021-12-28T15:35:20Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.2.2/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.2.2",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.2.2",
		"body": ""
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55953791",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55953791/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/55953791/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.3.0-rc8",
		"id": 55953791,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DVcl_",
		"tag_name": "1.3.0-rc8",
		"target_commitish": "rnd/version-management",
		"name": "1.3.0-rc8",
		"draft": false,
		"prerelease": true,
		"created_at": "2021-12-24T11:59:54Z",
		"published_at": "2021-12-24T13:43:46Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52511641",
				"id": 52511641,
				"node_id": "RA_kwDOCwMSYc4DIUOZ",
				"name": "compatibility.json",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 37,
				"download_count": 4,
				"created_at": "2021-12-24T13:48:34Z",
				"updated_at": "2021-12-24T13:48:35Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.0-rc8/compatibility.json"
			},
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52511639",
				"id": 52511639,
				"node_id": "RA_kwDOCwMSYc4DIUOX",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1556806,
				"download_count": 5,
				"created_at": "2021-12-24T13:48:34Z",
				"updated_at": "2021-12-24T13:48:34Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.3.0-rc8/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.3.0-rc8",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.3.0-rc8",
		"body": ""
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55741142",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55741142/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/55741142/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.2.1",
		"id": 55741142,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DUorW",
		"tag_name": "1.2.1",
		"target_commitish": "master",
		"name": "1.2.1",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-21T12:04:51Z",
		"published_at": "2021-12-21T12:05:21Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52273292",
				"id": 52273292,
				"node_id": "RA_kwDOCwMSYc4DHaCM",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1535670,
				"download_count": 16,
				"created_at": "2021-12-21T12:14:04Z",
				"updated_at": "2021-12-21T12:14:04Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.2.1/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.2.1",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.2.1",
		"body": "## What's Changed\r\n* Refresh identity balance on page reload by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/248\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.2.0...1.2.1",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55538503",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55538503/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/55538503/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.2.0",
		"id": 55538503,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DT3NH",
		"tag_name": "1.2.0",
		"target_commitish": "master",
		"name": "1.2.0",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-17T12:07:04Z",
		"published_at": "2021-12-17T12:16:34Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/52009361",
				"id": 52009361,
				"node_id": "RA_kwDOCwMSYc4DGZmR",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1538826,
				"download_count": 11,
				"created_at": "2021-12-17T12:21:31Z",
				"updated_at": "2021-12-17T12:21:31Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.2.0/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.2.0",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.2.0",
		"body": "## What's Changed\r\n* TX History and refactoring by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/247\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.1.5...1.2.0",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55038316",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/55038316/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/55038316/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.5",
		"id": 55038316,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DR9Fs",
		"tag_name": "1.1.5",
		"target_commitish": "master",
		"name": "1.1.5",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-10T11:23:00Z",
		"published_at": "2021-12-10T11:23:21Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51467861",
				"id": 51467861,
				"node_id": "RA_kwDOCwMSYc4DEVZV",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1526741,
				"download_count": 10,
				"created_at": "2021-12-10T11:32:41Z",
				"updated_at": "2021-12-10T11:32:42Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.5/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.5",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.5",
		"body": ""
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54867788",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54867788/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54867788/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.4",
		"id": 54867788,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DRTdM",
		"tag_name": "1.1.4",
		"target_commitish": "master",
		"name": "1.1.4",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-08T12:17:33Z",
		"published_at": "2021-12-08T12:18:41Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51298126",
				"id": 51298126,
				"node_id": "RA_kwDOCwMSYc4DDr9O",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1526256,
				"download_count": 7,
				"created_at": "2021-12-08T12:27:09Z",
				"updated_at": "2021-12-08T12:27:09Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.4/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.4",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.4",
		"body": "## What's Changed\r\n* Don't show registration modal right away by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/244\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.1.2...1.1.4",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54866023",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54866023/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54866023/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.3",
		"id": 54866023,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DRTBn",
		"tag_name": "1.1.3",
		"target_commitish": "master",
		"name": "1.1.3",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-08T11:06:21Z",
		"published_at": "2021-12-08T11:53:45Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51296495",
				"id": 51296495,
				"node_id": "RA_kwDOCwMSYc4DDrjv",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1526162,
				"download_count": 3,
				"created_at": "2021-12-08T11:58:25Z",
				"updated_at": "2021-12-08T11:58:25Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.3/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.3",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.3",
		"body": "## What's Changed\r\n* Improvements registration retry by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/243\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.1.1...1.1.3",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54863115",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54863115/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54863115/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.2",
		"id": 54863115,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DRSUL",
		"tag_name": "1.1.2",
		"target_commitish": "master",
		"name": "1.1.2",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-08T11:06:21Z",
		"published_at": "2021-12-08T11:07:26Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51294008",
				"id": 51294008,
				"node_id": "RA_kwDOCwMSYc4DDq84",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1527082,
				"download_count": 2,
				"created_at": "2021-12-08T11:15:48Z",
				"updated_at": "2021-12-08T11:15:49Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.2/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.2",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.2",
		"body": "## What's Changed\r\n* Registration retry by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/243\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.1.1...1.1.2",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54696879",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54696879/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54696879/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.1",
		"id": 54696879,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DQpuv",
		"tag_name": "1.1.1",
		"target_commitish": "master",
		"name": "1.1.1",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-06T10:35:33Z",
		"published_at": "2021-12-06T10:36:18Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51116570",
				"id": 51116570,
				"node_id": "RA_kwDOCwMSYc4DC_oa",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1530481,
				"download_count": 3,
				"created_at": "2021-12-06T10:45:06Z",
				"updated_at": "2021-12-06T10:45:12Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.1/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.1",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.1",
		"body": "## What's Changed\r\n* Bump axios from 0.21.1 to 0.21.4 by @dependabot in https://github.com/mysteriumnetwork/dvpn-web/pull/227\r\n* Use state to determine radio form active option by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/242\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.1.0...1.1.1",
		"mentions_count": 2
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54690248",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54690248/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54690248/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.1.0",
		"id": 54690248,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DQoHI",
		"tag_name": "1.1.0",
		"target_commitish": "master",
		"name": "1.1.0",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-06T08:45:35Z",
		"published_at": "2021-12-06T08:53:29Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/51110405",
				"id": 51110405,
				"node_id": "RA_kwDOCwMSYc4DC-IF",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1530126,
				"download_count": 2,
				"created_at": "2021-12-06T09:00:40Z",
				"updated_at": "2021-12-06T09:00:40Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.1.0/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.1.0",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.1.0",
		"body": "## What's Changed\r\n* Refactor Onboarding by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/238\r\n* Update Unsettled Earnings help text by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/240\r\n* Check for provider free registration eligibility by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/241\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.0.4...1.1.0",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54568959",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54568959/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54568959/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.0.4",
		"id": 54568959,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DQKf_",
		"tag_name": "1.0.4",
		"target_commitish": "master",
		"name": "1.0.4",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-03T11:00:19Z",
		"published_at": "2021-12-03T11:07:19Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50912153",
				"id": 50912153,
				"node_id": "RA_kwDOCwMSYc4DCNuZ",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1519456,
				"download_count": 3,
				"created_at": "2021-12-03T11:11:59Z",
				"updated_at": "2021-12-03T11:12:00Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.0.4/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.0.4",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.0.4",
		"body": "## What's Changed\r\n* modified registration fee logic by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/237\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/1.0.3...1.0.4",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54506016",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54506016/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54506016/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.0.3",
		"id": 54506016,
		"author": {
			"login": "Guillembonet",
			"id": 713345,
			"node_id": "MDQ6VXNlcjcxMzM0NQ==",
			"avatar_url": "https://avatars.githubusercontent.com/u/713345?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/Guillembonet",
			"html_url": "https://github.com/Guillembonet",
			"followers_url": "https://api.github.com/users/Guillembonet/followers",
			"following_url": "https://api.github.com/users/Guillembonet/following{/other_user}",
			"gists_url": "https://api.github.com/users/Guillembonet/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/Guillembonet/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/Guillembonet/subscriptions",
			"organizations_url": "https://api.github.com/users/Guillembonet/orgs",
			"repos_url": "https://api.github.com/users/Guillembonet/repos",
			"events_url": "https://api.github.com/users/Guillembonet/events{/privacy}",
			"received_events_url": "https://api.github.com/users/Guillembonet/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DP7Ig",
		"tag_name": "1.0.3",
		"target_commitish": "master",
		"name": "1.0.3",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-02T15:30:32Z",
		"published_at": "2021-12-02T15:31:23Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50841032",
				"id": 50841032,
				"node_id": "RA_kwDOCwMSYc4DB8XI",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1519569,
				"download_count": 1,
				"created_at": "2021-12-02T15:41:10Z",
				"updated_at": "2021-12-02T15:41:11Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.0.3/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.0.3",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.0.3",
		"body": "## What's Changed\r\n* Mainnet -> Master by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/235\r\n* fix onboarding and add dynamic registration fee by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/236\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/0.4.7...1.0.3",
		"mentions_count": 2
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54483748",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54483748/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54483748/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.0.2-rc0",
		"id": 54483748,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DP1sk",
		"tag_name": "1.0.2-rc0",
		"target_commitish": "master",
		"name": "1.0.2-rc0",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-02T10:05:58Z",
		"published_at": "2021-12-02T10:57:35Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50819636",
				"id": 50819636,
				"node_id": "RA_kwDOCwMSYc4DB3I0",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1518975,
				"download_count": 1,
				"created_at": "2021-12-02T11:04:58Z",
				"updated_at": "2021-12-02T11:04:58Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.0.2-rc0/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.0.2-rc0",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.0.2-rc0",
		"body": "## What's Changed\r\n* Mainnet -> Master by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/235\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/0.4.7...1.0.2-rc0",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54409641",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54409641/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54409641/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/0.4.9",
		"id": 54409641,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DPjmp",
		"tag_name": "0.4.9",
		"target_commitish": "testnet3",
		"name": "0.4.9",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-01T13:06:15Z",
		"published_at": "2021-12-01T13:32:09Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50741719",
				"id": 50741719,
				"node_id": "RA_kwDOCwMSYc4DBkHX",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1506336,
				"download_count": 2,
				"created_at": "2021-12-01T14:21:08Z",
				"updated_at": "2021-12-01T14:21:09Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/0.4.9/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/0.4.9",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/0.4.9",
		"body": "- Fix MainNet migration Link\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/0.4.8...0.4.9"
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54406867",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/54406867/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/54406867/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/0.4.8",
		"id": 54406867,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DPi7T",
		"tag_name": "0.4.8",
		"target_commitish": "testnet3",
		"name": "0.4.8",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-12-01T12:54:53Z",
		"published_at": "2021-12-01T12:55:30Z",
		"assets": [],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/0.4.8",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/0.4.8",
		"body": "## What's Changed\r\n* Kill bounty widget by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/233\r\n\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/0.4.7...0.4.8",
		"mentions_count": 1
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/53849695",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/53849695/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/53849695/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.0.2",
		"id": 53849695,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DNa5f",
		"tag_name": "1.0.2",
		"target_commitish": "mainnet",
		"name": "1.0.2",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-11-22T15:27:18Z",
		"published_at": "2021-11-22T15:33:36Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50054258",
				"id": 50054258,
				"node_id": "RA_kwDOCwMSYc4C-8Ry",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1515724,
				"download_count": 3,
				"created_at": "2021-11-22T15:59:09Z",
				"updated_at": "2021-11-22T15:59:10Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.0.2/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.0.2",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.0.2",
		"body": "- Update Terms and Conditions"
	},
	{
		"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/53839105",
		"assets_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/53839105/assets",
		"upload_url": "https://uploads.github.com/repos/mysteriumnetwork/dvpn-web/releases/53839105/assets{?name,label}",
		"html_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/tag/1.0.1",
		"id": 53839105,
		"author": {
			"login": "mdomasevicius",
			"id": 20511486,
			"node_id": "MDQ6VXNlcjIwNTExNDg2",
			"avatar_url": "https://avatars.githubusercontent.com/u/20511486?v=4",
			"gravatar_id": "",
			"url": "https://api.github.com/users/mdomasevicius",
			"html_url": "https://github.com/mdomasevicius",
			"followers_url": "https://api.github.com/users/mdomasevicius/followers",
			"following_url": "https://api.github.com/users/mdomasevicius/following{/other_user}",
			"gists_url": "https://api.github.com/users/mdomasevicius/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/mdomasevicius/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/mdomasevicius/subscriptions",
			"organizations_url": "https://api.github.com/users/mdomasevicius/orgs",
			"repos_url": "https://api.github.com/users/mdomasevicius/repos",
			"events_url": "https://api.github.com/users/mdomasevicius/events{/privacy}",
			"received_events_url": "https://api.github.com/users/mdomasevicius/received_events",
			"type": "User",
			"site_admin": false
		},
		"node_id": "RE_kwDOCwMSYc4DNYUB",
		"tag_name": "1.0.1",
		"target_commitish": "mainnet",
		"name": "1.0.1",
		"draft": false,
		"prerelease": false,
		"created_at": "2021-11-22T13:16:34Z",
		"published_at": "2021-11-22T13:17:45Z",
		"assets": [
			{
				"url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/releases/assets/50043500",
				"id": 50043500,
				"node_id": "RA_kwDOCwMSYc4C-5ps",
				"name": "dist.tar.gz",
				"label": "",
				"uploader": {
					"login": "MysteriumTeam",
					"id": 42934344,
					"node_id": "MDQ6VXNlcjQyOTM0MzQ0",
					"avatar_url": "https://avatars.githubusercontent.com/u/42934344?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/MysteriumTeam",
					"html_url": "https://github.com/MysteriumTeam",
					"followers_url": "https://api.github.com/users/MysteriumTeam/followers",
					"following_url": "https://api.github.com/users/MysteriumTeam/following{/other_user}",
					"gists_url": "https://api.github.com/users/MysteriumTeam/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/MysteriumTeam/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/MysteriumTeam/subscriptions",
					"organizations_url": "https://api.github.com/users/MysteriumTeam/orgs",
					"repos_url": "https://api.github.com/users/MysteriumTeam/repos",
					"events_url": "https://api.github.com/users/MysteriumTeam/events{/privacy}",
					"received_events_url": "https://api.github.com/users/MysteriumTeam/received_events",
					"type": "User",
					"site_admin": false
				},
				"content_type": "application/octet-stream",
				"state": "uploaded",
				"size": 1515748,
				"download_count": 3,
				"created_at": "2021-11-22T13:26:23Z",
				"updated_at": "2021-11-22T13:26:23Z",
				"browser_download_url": "https://github.com/mysteriumnetwork/dvpn-web/releases/download/1.0.1/dist.tar.gz"
			}
		],
		"tarball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/tarball/1.0.1",
		"zipball_url": "https://api.github.com/repos/mysteriumnetwork/dvpn-web/zipball/1.0.1",
		"body": "## What's Changed\r\n* Changed table to react table by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/214\r\n* Move everything into forms + refactors by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/215\r\n* Technical debt by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/216\r\n* Fix email optional text by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/218\r\n* Modified chart title to better describe it by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/222\r\n* Registration flow adjustments by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/224\r\n* Bump mysterium-vpn-js by @mdomasevicius in https://github.com/mysteriumnetwork/dvpn-web/pull/225\r\n* fix authentication check bug by @Guillembonet in https://github.com/mysteriumnetwork/dvpn-web/pull/228\r\n* Fix mystnodes.com URL by @Donatas-MN in https://github.com/mysteriumnetwork/dvpn-web/pull/229\r\n\r\n## New Contributors\r\n* @Donatas-MN made their first contribution in https://github.com/mysteriumnetwork/dvpn-web/pull/229\r\n\r\n**Full Changelog**: https://github.com/mysteriumnetwork/dvpn-web/compare/0.4.6...1.0.1",
		"mentions_count": 3
	}
]
`
